### PR TITLE
Bump Qt to 5.12.9 to match MSYS build and use more variables

### PR DESCRIPTION
**Pull request by elecpower**

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Just as a possibility: why not using `aqtinstall` as on the other architectures? That might save us the trouble of patching the binaries. On the other hand, it would require setting all the variables correctly for that installation to be found correctly.

**Comment by elecpower** [comment]
'Baby steps' version consistency across OSes then look at unifying if that's where you wish to go.

**Comment by raphaelcoeffic** [comment]
Well, the issue right now seems to be that the build fails because of some naming issue with the libs installed. This is something that is taken care of by the other installer.

**Comment by elecpower** [comment]
Didn't know it was failing on the git builds. I tested the docker image on Ubuntu 20.04 for my compiles of all builds and no failures.

**Comment by elecpower** [comment]
So got past my mistake but now failing exporting the image with 403 permission denied. Not obvious to me so over to you.

**Comment by elecpower** [comment]
> Just as a possibility: why not using `aqtinstall` as on the other architectures? That might save us the trouble of patching the binaries. On the other hand, it would require setting all the variables correctly for that installation to be found correctly.

Found a docker image albeit older OS and the dev's github project so will see about getting ETX image to use aqtinstall so fingers crossed.

**Comment by pfeerick** [comment]
I think that is because the checks action needs some tweaks as it isn't taking into account that it is being used to *check* a PR, and is trying to actually publish, which it should not be allowed to do, hence the failure ;)

**Comment by raphaelcoeffic** [comment]
@elecpower Thx! This has been merged into `main` manually.

**Pull request closed without merging**
